# Generated by Django 6.0.4 on 2026-05-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_organiz_3cab48_idx',
            old_name='projects_pr_organiz_6f3a21_idx',
        ),
    ]
