# Generated by Django 6.0.4 on 2026-05-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_projects_pr_organiz_6f3a21_idx_projects_pr_organiz_3cab48_idx'),
        ('workspaces', '0010_add_workspace_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace'),
        ),
    ]
