"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8t*fq43cq-ipc=c4ez68qk5)1l%f)h-*b$i3w-8w%*#f+*l!i9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# CORS Configuration: Allow frontend origins
# In development, CORS_ALLOW_ALL_ORIGINS=True is the safest option to debug.
# In production, specify exact origins. We support both modes via environment variable.
CORS_ALLOW_ALL_ORIGINS = DEBUG or os.environ.get('CORS_ALLOW_ALL_ORIGINS', '').lower() == 'true'

# Fallback to explicit origins if CORS_ALLOW_ALL_ORIGINS is False
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
]

# CORS additional headers: allow credentials with credentials=true requests
CORS_ALLOW_CREDENTIALS = True

# CORS allow all methods for preflight
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
    'HEAD',
]

# Allow common headers in preflight requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-request-id',
]

# Expose response headers to the frontend
CORS_EXPOSE_HEADERS = [
    'x-request-id',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'apps.core',
    'apps.organizations',
    'apps.workspaces',
    'apps.projects',
    'apps.tasks',
    'apps.comments',
    'apps.notifications',
    'apps.ai_assistant',
    'apps.audit_logs',
    'apps.user_profiles',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'config.middleware.RequestLoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'config.middleware.JWTAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if "test" in sys.argv:
    # Use in-memory SQLite for test runs to avoid requiring a running Postgres.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    # Local development / runserver use Postgres
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "collabai_db"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "12345678"),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }


# Cache: Redis when REDIS_URL is set, in-process LocMem otherwise so dev/tests
# work without a running Redis. Default cache TTL is 5 min for list endpoints.
REDIS_URL = os.environ.get('REDIS_URL')
CACHE_DEFAULT_TIMEOUT = int(os.environ.get('CACHE_DEFAULT_TIMEOUT', 300))
METRICS_CACHE_TIMEOUT = int(os.environ.get('METRICS_CACHE_TIMEOUT', 60))

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
            },
            'KEY_PREFIX': 'collabai',
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
        }
    }
    DJANGO_REDIS_IGNORE_EXCEPTIONS = True
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'collabai-default',
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'common.pagination.StandardPagination',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CollabAI API',
    'DESCRIPTION': 'API documentation for CollabAI.',
    'VERSION': '1.0.0',
    'SECURITY': [{'bearerAuth': []}],
    'ENUM_NAME_OVERRIDES': {
        'MemberRoleEnum': [
            ('admin', 'Admin'),
            ('manager', 'Manager'),
            ('member', 'Member'),
        ],
    },
    'COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

API_JWT_ENFORCE_PREFIX = '/api/v1/'
API_JWT_PUBLIC_PATHS = (
    '/api/v1/auth/register',
    '/api/v1/auth/login',
    '/api/v1/auth/refresh',
    '/api/v1/health',
)
API_JWT_ROLE_REQUIREMENTS = ()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'config.middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.ai_assistant': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# --- RAG / AI (local dev) ---
GROQ_API_KEY = (os.environ.get('GROQ_API_KEY') or '').strip().strip('"').strip("'")
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'llama-3.1-8b-instant')
RAG_EMBEDDING_MODEL = os.environ.get(
    'RAG_EMBEDDING_MODEL',
    'sentence-transformers/all-MiniLM-L6-v2',
)
RAG_EMBEDDING_DIMS = int(os.environ.get('RAG_EMBEDDING_DIMS', '384'))
RAG_VECTOR_INDEX_NAME = os.environ.get('RAG_VECTOR_INDEX_NAME', 'collabai_rag')
RAG_TOP_K_DEFAULT = int(os.environ.get('RAG_TOP_K_DEFAULT', '5'))
RAG_AUTO_INDEX = os.environ.get('RAG_AUTO_INDEX', 'true').lower() == 'true'
# Use in-memory vector search when Redis Stack / RediSearch is unavailable.
RAG_FORCE_MEMORY_STORE = os.environ.get('RAG_FORCE_MEMORY_STORE', '').lower() == 'true'

# --- Celery (optional; eager mode works without a worker) ---
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL or 'redis://127.0.0.1:6379/1')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TASK_ALWAYS_EAGER = os.environ.get(
    'CELERY_TASK_ALWAYS_EAGER',
    'true' if DEBUG else 'false',
).lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True

# Celery Beat — Team Pulse daily standup (9:00). Requires: celery -A config beat
from celery.schedules import crontab  # noqa: E402

TEAM_PULSE_STANDUP_HOUR = int(os.environ.get('TEAM_PULSE_STANDUP_HOUR', '9'))

CELERY_BEAT_SCHEDULE = {
    'team-pulse-daily-standup': {
        'task': 'apps.ai_assistant.tasks_team_pulse.run_daily_standup_agent',
        'schedule': crontab(hour=TEAM_PULSE_STANDUP_HOUR, minute=0),
    },
}
