# Generated by Django 6.0.4 on 2026-05-18 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0002_seed_default_task_statuses'),
        ('workspaces', '0003_alter_role_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlanDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_description', models.TextField()),
                ('sprint_count', models.PositiveSmallIntegerField(default=3)),
                ('team_members', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=32)),
                ('ai_raw_output', models.JSONField(blank=True, default=dict)),
                ('validation_meta', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_drafts', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_plan_drafts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_plan_drafts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('sprint_number', models.PositiveSmallIntegerField(default=1)),
                ('story_points', models.PositiveSmallIntegerField(default=3)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('suggested_assignee_role', models.CharField(blank=True, max_length=100)),
                ('depends_on', models.JSONField(blank=True, default=list)),
                ('covers_requirements', models.JSONField(blank=True, default=list)),
                ('goal', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('acceptance_criteria', models.JSONField(blank=True, default=list)),
                ('technical_notes', models.TextField(blank=True)),
                ('rendered_body', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_planned_tasks', to='tasks.task')),
                ('suggested_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_tasks', to='ai_assistant.projectplandraft')),
            ],
            options={
                'ordering': ['order', 'slug'],
                'unique_together': {('plan', 'slug')},
            },
        ),
    ]
