# Generated by Django 6.0.4 on 2026-05-19 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_projectplandraft_target_project'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplandraft',
            name='target_project',
            field=models.ForeignKey(blank=True, help_text='If set, approval adds tasks to this project instead of creating a new one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_plan_drafts', to='projects.project'),
        ),
    ]
