# Generated by Django 6.0.4 on 2026-05-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_migrate_to_organization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teampulsealert',
            new_name='ai_assistan_organiz_45e7b0_idx',
            old_name='ai_assistan_organiz_4c9e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='teampulsereport',
            new_name='ai_assistan_organiz_b4a29f_idx',
            old_name='ai_assistan_organiz_8a1f2d_idx',
        ),
        migrations.AlterField(
            model_name='githuborganizationconfig',
            name='member_github_logins',
            field=models.JSONField(blank=True, default=dict, help_text='Map of user_id (str) → GitHub username.'),
        ),
    ]
