# Generated by Django 6.0.4 on 2026-05-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_update_org_member_roles_to_4role_rbac'),
        ('tasks', '0002_seed_default_task_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='label',
            index=models.Index(fields=['organization', 'name'], name='tasks_label_organiz_1c000c_idx'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_label_name_per_organization'),
        ),
    ]
