# Generated by Django 6.0.4 on 2026-05-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_teammember_workspaceinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('member', 'Member')], max_length=100),
        ),
    ]
