# Generated by Django 6.0.4 on 2026-05-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_seed_job_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='task_categories',
            field=models.JSONField(blank=True, default=list, help_text='AI task categories this role typically owns (e.g. backend, api, auth).'),
        ),
    ]
