# Generated by Django 6.0.4 on 2026-05-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_jobrole_task_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkspaceInvite',
        ),
    ]
