# Generated by Django 6.0.4 on 2026-05-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_workspace_deleted_at_workspace_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
