# Generated by Django 6.0.4 on 2026-05-20 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationmember'),
        ('workspaces', '0007_delete_workspaceinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('org_admin', 'Organization Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('org_admin', 'Organization Admin'), ('workspace_admin', 'Workspace Admin'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organizations.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_invites', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
