# Generated by Django 6.0.4 on 2026-05-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationmember_role_organizationinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
